services:
  app:
    # Constrói a imagem a partir do Dockerfile no diretório atual.
    build: .
    container_name: fernando1
    ports:
      # Mapeia a porta 8000 do host para a porta 8000 do contêiner.
      - "8000:8000"
    volumes:
      # Monta o diretório atual no contêiner. Isso permite o hot-reload e
      # persiste o banco de dados SQLite (escola.db) no seu computador.
      - .:/app
    # O comando `uvicorn` com `--reload` é ideal para desenvolvimento.
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload

